# Generated by Django 3.1.3 on 2021-03-21 18:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('elevation', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='asset_photo/')),
                ('comissioning_date', models.DateField(blank=True, null=True)),
                ('decommission_date', models.DateField(blank=True, null=True)),
                ('active', models.CharField(blank=True, choices=[('Yes', 'Active'), ('No', 'Inactive'), ('Maintenance', 'Maintenance')], max_length=11, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('industry', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=75)),
                ('office_location', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('surname', models.CharField(max_length=75)),
                ('title', models.CharField(blank=True, max_length=75, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.IntegerField(blank=True, null=True, unique=True)),
                ('office_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.office')),
            ],
        ),
        migrations.CreateModel(
            name='AssetTypeSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.ImageField(unique=True, upload_to='symbol_img/')),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.assettype')),
            ],
        ),
        migrations.CreateModel(
            name='AssetTypeProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('dtype', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.assettype')),
            ],
        ),
        migrations.CreateModel(
            name='AssetPropertyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.asset')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.assettypeproperty')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.assettype'),
        ),
    ]
