# Generated by Django 3.1.7 on 2021-05-15 13:30

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asset_Life_Cycle', '0002_lifecycle_asset_type'),
        ('crt_ast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='active',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactiveive', 'Inactive'), ('Maintenance', 'Maintenance')], max_length=11, null=True),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('comissioning_date', models.DateField(blank=True, null=True)),
                ('decommission_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance', 'Maintenance')], max_length=11, null=True)),
                ('deneme', models.BinaryField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='asset_photo/')),
                ('symbol', models.FilePathField(blank=True, null=True, path='crt_ast/static/Cesium/Build/Cesium/Assets/Textures/maki/')),
                ('markersize', models.FloatField(blank=True, default=1.0, null=True)),
                ('markercolor', colorfield.fields.ColorField(blank=True, choices=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#808080', 'grey'), ('#FFFF00', 'yellow'), ('#FF0000', 'red'), ('#0000FF', 'blue'), ('#008000', 'green'), ('#FFC0CB', 'pink')], default='#FFFFFF', max_length=18, null=True)),
                ('lc_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asset_Life_Cycle.lifecyclephase')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.assettype')),
            ],
        ),
    ]
