# Generated by Django 3.1.7 on 2021-03-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='markercolor',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='markersymbol',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
