# Generated by Django 3.1.7 on 2021-05-22 15:42

import colorfield.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asset_Life_Cycle', '0003_auto_20210522_1842'),
        ('crt_ast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='active',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactiveive', 'Inactive'), ('Maintenance', 'Maintenance')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='comissioning_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='decommission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
        migrations.AlterField(
            model_name='asset',
            name='lc_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asset_Life_Cycle.lifecyclephase'),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='office_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crt_ast.office'),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('comissioning_date', models.DateField(blank=True, null=True)),
                ('decommission_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='asset_photo/')),
                ('symbol', models.FilePathField(blank=True, null=True, path='crt_ast/static/Cesium/Build/Cesium/Assets/Textures/maki/')),
                ('markersize', models.FloatField(blank=True, default=1.0, null=True)),
                ('markercolor', colorfield.fields.ColorField(blank=True, choices=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#808080', 'grey'), ('#FFFF00', 'yellow'), ('#FF0000', 'red'), ('#0000FF', 'blue'), ('#008000', 'green'), ('#FFC0CB', 'pink')], default='#FFFFFF', max_length=18, null=True)),
                ('lc_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asset_Life_Cycle.lifecyclephase')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.assettype')),
            ],
        ),
    ]
