# Generated by Django 3.1.7 on 2021-03-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0002_auto_20210321_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='markersize',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
