# Generated by Django 3.1.3 on 2021-03-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0002_auto_20210314_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTypeSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.ImageField(upload_to='img/')),
                ('description', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
