# Generated by Django 3.1.7 on 2021-05-22 16:20

import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('Asset_Life_Cycle', '0004_auto_20210522_1920'),
        ('crt_ast', '0002_auto_20210522_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='comissioning_date',
            field=models.DateField(blank=True, null=True, verbose_name='Comissioning Date'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='decommission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Decommission Date'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='geom',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(32.73382, 39.865586), srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='lc_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asset_Life_Cycle.lifecyclephase', verbose_name='Life Cycle Phase'),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Office Location'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='office_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crt_ast.office', verbose_name='Office Info'),
        ),
    ]
