# Generated by Django 3.1.7 on 2021-03-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0003_asset_markersize'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='lon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
