# Generated by Django 3.1.7 on 2021-05-22 18:29

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0004_auto_20210522_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='markercolor',
            field=colorfield.fields.ColorField(blank=True, choices=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#808080', 'grey'), ('#FFFF00', 'yellow'), ('#FF0000', 'red'), ('#0000FF', 'blue'), ('#008000', 'green'), ('#FFA500', 'orange'), ('#d4f1f9', 'water')], default='#FFFFFF', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='markersize',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
    ]
