# Generated by Django 3.1.3 on 2021-03-14 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0004_delete_assettypesymbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTypeSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.ImageField(upload_to='img/')),
                ('description', models.CharField(max_length=256, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.assettype')),
            ],
        ),
    ]
