# Generated by Django 3.1.3 on 2021-03-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0005_assettypesymbol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
