# Generated by Django 3.1.7 on 2021-03-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0006_delete_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('elevation', models.IntegerField()),
                ('photo', models.ImageField(upload_to='asset_photo/')),
                ('comissioning_date', models.DateField()),
                ('decommission_date', models.DateField()),
                ('active', models.CharField(choices=[('Yes', 'Active'), ('No', 'Inactive'), ('Maintenance', 'Maintenance')], max_length=11)),
                ('description', models.CharField(max_length=256, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.assettype')),
            ],
        ),
    ]
