# Generated by Django 3.1.7 on 2021-03-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0008_assetpropertyvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='comissioning_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='decommission_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='elevation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='photo',
            field=models.ImageField(null=True, upload_to='asset_photo/'),
        ),
    ]
