# Generated by Django 3.1.7 on 2021-05-23 11:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0008_auto_20210522_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSpaceLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
    ]
