# Generated by Django 3.1.7 on 2021-05-23 11:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0010_auto_20210523_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
