# Generated by Django 3.1.7 on 2021-03-14 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0011_auto_20210314_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('surname', models.CharField(max_length=75)),
                ('title', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('office_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.office')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('surname', models.CharField(max_length=75)),
                ('title', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('office_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.office')),
                ('reports_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.seniorstaff')),
            ],
        ),
    ]
