# Generated by Django 3.1.7 on 2021-05-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0012_auto_20210523_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='address',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='geom',
        ),
    ]
