# Generated by Django 3.1.7 on 2021-03-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0012_seniorstaff_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetpropertyvalue',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assetpropertyvalue',
            name='property',
        ),
        migrations.RemoveField(
            model_name='seniorstaff',
            name='office_info',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='office_info',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='reports_to',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='AssetPropertyValue',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.DeleteModel(
            name='SeniorStaff',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
