# Generated by Django 3.1.7 on 2021-05-23 12:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0013_auto_20210523_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferenceSpaceLocation',
        ),
        migrations.AddField(
            model_name='asset',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
