# Generated by Django 3.1.7 on 2021-03-14 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0013_auto_20210314_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('elevation', models.IntegerField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='asset_photo/')),
                ('comissioning_date', models.DateField(null=True)),
                ('decommission_date', models.DateField(null=True)),
                ('active', models.CharField(choices=[('Yes', 'Active'), ('No', 'Inactive'), ('Maintenance', 'Maintenance')], max_length=11)),
                ('description', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=75)),
                ('office_location', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('description', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeniorStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('surname', models.CharField(max_length=75)),
                ('title', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('office_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.office')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('surname', models.CharField(max_length=75)),
                ('title', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('office_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.office')),
                ('reports_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.seniorstaff')),
            ],
        ),
        migrations.CreateModel(
            name='AssetPropertyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.asset')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.assettypeproperty')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='dataEntryStaff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.staff'),
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.assettype'),
        ),
    ]
