# Generated by Django 3.1.7 on 2021-03-14 21:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0015_auto_20210315_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('elevation', models.IntegerField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='asset_photo/')),
                ('comissioning_date', models.DateField(null=True)),
                ('decommission_date', models.DateField(null=True)),
                ('active', models.CharField(choices=[('Yes', 'Active'), ('No', 'Inactive'), ('Maintenance', 'Maintenance')], max_length=11)),
                ('description', models.CharField(max_length=256, null=True)),
                ('dataEntryStaff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.staff')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.assettype')),
            ],
        ),
        migrations.CreateModel(
            name='AssetPropertyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.asset')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_ast.assettypeproperty')),
            ],
        ),
    ]
