# Generated by Django 3.1.7 on 2021-03-20 19:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0017_auto_20210319_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(srid=4326),
        ),
    ]
