# Generated by Django 3.1.7 on 2021-03-20 19:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0018_auto_20210320_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
