# Generated by Django 3.1.7 on 2021-05-23 13:12

import django.contrib.gis.geos.point
from django.db import migrations
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0019_auto_20210523_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MushroomSpot',
        ),
        migrations.AlterField(
            model_name='asset',
            name='geom',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(32.73382, 39.865586), srid=4326, verbose_name='Location'),
        ),
    ]
