# Generated by Django 3.1.7 on 2021-05-23 14:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0022_auto_20210523_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='elevation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
