# Generated by Django 3.1.7 on 2021-03-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0025_auto_20210321_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/asset_photo/'),
        ),
    ]
