# Generated by Django 3.1.7 on 2021-05-24 08:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0025_auto_20210524_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='markercolor',
            field=colorfield.fields.ColorField(blank=True, choices=[('#FFFFFF90', 'white'), ('#00000090', 'black'), ('#80808090', 'grey'), ('#FFFF0090', 'yellow'), ('#FF000090', 'red'), ('#0000FF90', 'blue'), ('#00800090', 'green'), ('#FFA50090', 'orange'), ('#87CEEB90', 'light blue')], default='#FFFFFF', max_length=18, null=True),
        ),
    ]
