# Generated by Django 3.1.7 on 2021-03-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_ast', '0026_auto_20210321_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='photo',
            field=models.ImageField(null=True, upload_to='templates/images/asset_photo/'),
        ),
    ]
