# Generated by Django 3.1.7 on 2021-05-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_addtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addTask',
        ),
    ]
